language: rust
rust: stable
cache: cargo
sudo: required
env:
  global:
  - PROJECT: torchbear
matrix:
  include:
  - os: linux
    rust: stable
    env:
    - ARCH=x86_64
    - PLATFORM=linux
    - CHANNEL=stable
    services: docker
    script: echo "cargo test temporarily disabled"
    before_deploy:
    - docker build -t build-${PROJECT}-image .
    - docker run -it --name build-${PROJECT} build-${PROJECT}-image
    - docker cp build-${PROJECT}:/home/rust/src/target/x86_64-unknown-linux-musl/release/${PROJECT}
      ${PROJECT}
    - docker rm build-${PROJECT}
    - docker rmi build-${PROJECT}-image
    - zip ${PROJECT}-${TRAVIS_TAG}-${ARCH}-${PLATFORM}-${CHANNEL}.zip ${PROJECT}
    - chmod +x torchbear
    - ./torchbear &
deploy:
  provider: releases
  api_key:
    secure: W3ShbjNyAdYqTopB46k4cTKKK9Sog1Xos7EaHFGMexARFb/ujJM+leIiKmz19LTM25hYhb8aMCrbU/dBt+ATG2kZcnEysEVX2pCtQp0YfOq3QKyCF6CmxGIm7ZsilhOuudWc1e6ahij2MR9mAdzMG1jeezGWsymLFdVyCpCv1+ysy8vXUP7RzV/Ly+BplzadHwRFSxwb9V2lzmmX9zOeHo2a2WjzxsqZC9sawAQhY3xZz7jDN98jbRmUi0K7xRQMQEqN0HOA5qN4sl3jBHYFX8gvBn33CCyf8908CnuFCwZit4kiF+drc6D0XRnBU7ynrVKV0lQjcvH4m2hzKH5UwWaRMViHj9/6Qrt+h4x4em4HEjNZY6esT0iw0dKdeLuT0EIa+j5uw56R5uK2ozssGgP9brNtnsRxvbllJHmg5D/iYUPyelKyTep0uVXFol7+SaM3UVd0+ag3bvpbNwoCqz+YLQ8NwW7nftmCikCTXODhkw5Rlec/KrjwmIWG9VVZNRH2MI0rG+Jjnm/BKeTyWDi2aJ77gUTMdDv1SmxfwjD80jHZJPYhXqTUjbb76Y20hPRNfqJdzuvGVREzmOoVKcdDzwmc9HopGqGWCNcPUFsj7DYWpx7VZyN8vtakJEXvMP49uzfccnSSaKRMh+fkDD9OcIaNeFEgglgzSYSXSPE=
  file_glob: true
  file: 
  - "${PROJECT}-${TRAVIS_TAG}-${ARCH}-${PLATFORM}-${CHANNEL}.*"
  - "torchbear.sig"
  skip_cleanup: true
  on:
    repo: sh-zam/torchbear
    tags: true
branches:
  only:
  - master
  - "/.*/"
  - "/^\\d+\\.\\d+\\.\\d+.*$/"
notifications:
  email:
    on_success: never
before_install:
- openssl aes-256-cbc -K $encrypted_d833950d04bb_key -iv $encrypted_d833950d04bb_iv
  -in private_key.enc -out private_key -d
