[package]
name = "torchbear"
version = "0.1.3"
authors = ["Mitchell Tannenbaum <tannenbaum.mitchell@gmail.com>"]

[lib]
name = "torchbear_lib"
path = "src/lib.rs"

[[bin]]
name = "torchbear"
path = "src/main.rs"

[patch.crates-io]
openssl = { git = "https://github.com/ishitatsuyuki/rust-openssl", branch = "0.9.x" }

#[features]
#default = []
#log_bindings = []

[dependencies]
actix = "0.7"
actix-lua = { git = "https://github.com/Arnaz87/actix-lua.git" }
actix-web = "0.7"
futures = "0.1"
env_logger = "0.5"
tera = "0.11"
rlua = "0.15"
failure = "0.1"
failure_derive = "0.1"
serde = "1.0"
serde_yaml = "0.8"
rlua_serde = "0.2"
uuid = "0.6"
serde_urlencoded = "0.5"
comrak = "0.2"
serde_json = "1.0"
rust_sodium = "0.10"
base64 = "0.9"
config = "0.9"
clap = "2.32"
chrono = "0.4"
log = "0.4.5"
fern = { version = "0.5", features = ["colored"] }
colored = "1.6.1"
log-panics = "2.0"
